In [2]:
import pandas as pd 
import numpy as np 

In [3]:
df = pd.read_csv(r"D:\ML_Practice\NLP\Fake News Classifier\train.csv\train.csv")

In [4]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
df.shape

(20800, 5)

In [6]:
df['text'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It By Darrell Lucus on October 30, 2016 Subscribe Jason Chaffetz on the stump in American Fork, Utah ( image courtesy Michael Jolley, available under a Creative Commons-BY license) \nWith apologies to Keith Olbermann, there is no doubt who the Worst Person in The World is this week–FBI Director James Comey. But according to a House Democratic aide, it looks like we also know who the second-worst person is as well. It turns out that when Comey sent his now-infamous letter announcing that the FBI was looking into emails that may be related to Hillary Clinton’s email server, the ranking Democrats on the relevant committees didn’t hear about it from Comey. They found out via a tweet from one of the Republican committee chairmen. \nAs we now know, Comey notified the Republican chairmen and Democratic ranking members of the House Intelligence, Judiciary, and Oversight committees that his agency was reviewing emai

In [44]:
df = df.dropna()
X = df.drop('label',axis=1)
y = df['label']

In [46]:
y.shape

(18285,)

In [47]:

messages = df.copy()
messages.reset_index(inplace=True)

In [48]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
18280  Rapper T. I. unloaded on black celebrities who...      0  
18281  When the Green Bay Packers lost to the Washing...      0  
18282  The Macy’s of today grew from the union of sev...      0  
18283  NATO, Russia To Hold Parallel Exercises In Bal...      1  
18284    David Swanson is an author, activist, journa...      1  

[18285 rows x 6 columns]

In [49]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re 

ps = PorterStemmer()
corpus = []

for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [50]:
# Apply CountVectorizer
# Creating the Bag of words model 

from sklearn.feature_extraction.text import CountVectorizer 
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()

In [51]:
import tensorflow as tf 

In [52]:
#Vocabulary size 
vocab_size = 5000
# This implies that we create 5000 words dictonary where every present in the text given is available , the no. of words should be less than or eq to  5000 

In [53]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential 
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense 

In [54]:
onehot = [one_hot(words,vocab_size) for words in corpus]
onehot # This represents the specific index of the word according to the vocab_size we have arranged 

[[3102, 2495, 2621, 3964, 14, 2409, 2694, 1021, 4074, 440],
 [3573, 2626, 4745, 2628, 2416, 1772, 4466],
 [2102, 2778, 4390, 1392],
 [552, 1846, 1558, 3635, 1026, 86],
 [4175, 2416, 1675, 1693, 661, 4237, 2416, 1102, 2226, 50],
 [2097,
  605,
  3426,
  694,
  607,
  3297,
  4709,
  3494,
  231,
  1295,
  3105,
  1390,
  643,
  135,
  4466],
 [900, 4280, 785, 4257, 4138, 2718, 4578, 2782, 3643, 3748, 3786],
 [4095, 3604, 3018, 1265, 3078, 4453, 3297, 2628, 3643, 3748, 3786],
 [4420, 2176, 236, 2794, 1223, 3910, 1549, 1085, 3297, 3802],
 [3637, 2599, 3341, 1781, 4252, 1877, 538, 911],
 [3693, 1978, 158, 653, 4199, 2831, 3309, 2077, 2000, 138, 1317],
 [3635, 261, 14, 3910, 3297, 3078],
 [1196, 3850, 1450, 888, 16, 1586, 849, 150, 2354],
 [2324, 3309, 4963, 1889, 2948, 1713, 1468, 3643, 3748, 3786],
 [4125, 482, 502, 3604, 1105, 3643, 3748, 3786],
 [463, 448, 2600, 1231, 3669, 2637, 624, 1633, 4608, 1645],
 [3924, 398, 2626],
 [2355, 1173, 4655, 105, 3297, 4606, 1725, 4466],
 [922, 1653, 4

In [55]:
sen_length = 20 
docs = pad_sequences(onehot,padding='pre',maxlen=sen_length)
print(docs)   # pre implies that we are padding at front, maxlen is the size of the word  
# Making the lenngth of the sentences equal by padding zeros to the one hot encoding  

[[   0    0    0 ... 1021 4074  440]
 [   0    0    0 ... 2416 1772 4466]
 [   0    0    0 ... 2778 4390 1392]
 ...
 [   0    0    0 ... 3643 3748 3786]
 [   0    0    0 ... 1639  408 4177]
 [   0    0    0 ... 3053 4519 3495]]


In [56]:
# Model 

embedding_features = 40 
model = Sequential()
model.add(Embedding(vocab_size,embedding_features,input_length=sen_length))
model.add(LSTM(100))  # 1 lstm layer of 100 neurons
model.add(Dense(1,activation='sigmoid'))
# We added dense layer because this is a classification problem 
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [57]:
X_final = np.array(docs)
Y_final = np.array(y)

In [58]:
X_final.shape,Y_final.shape

((18285, 20), (18285,))

In [59]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X_final,Y_final,random_state=42)

In [60]:
# Model training 

model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
215/215 [==============================] - 7s 23ms/step - loss: 0.3219 - accuracy: 0.8511 - val_loss: 0.1926 - val_accuracy: 0.9127
Epoch 2/10
215/215 [==============================] - 4s 21ms/step - loss: 0.1329 - accuracy: 0.9475 - val_loss: 0.1967 - val_accuracy: 0.9182
Epoch 3/10
215/215 [==============================] - 4s 21ms/step - loss: 0.0916 - accuracy: 0.9656 - val_loss: 0.2250 - val_accuracy: 0.9156
Epoch 4/10
215/215 [==============================] - 5s 22ms/step - loss: 0.0614 - accuracy: 0.9791 - val_loss: 0.2962 - val_accuracy: 0.9103
Epoch 5/10
215/215 [==============================] - 5s 22ms/step - loss: 0.0379 - accuracy: 0.9880 - val_loss: 0.3385 - val_accuracy: 0.9027
Epoch 6/10
215/215 [==============================] - 4s 21ms/step - loss: 0.0237 - accuracy: 0.9921 - val_loss: 0.3391 - val_accuracy: 0.9088
Epoch 7/10
215/215 [==============================] - 5s 22ms/step - loss: 0.0138 - accuracy: 0.9959 - val_loss: 0.4830 - val_accuracy: 0.9094

In [67]:
y_pred = model.predict(X_test)

143/143 [==============================] - 0s 3ms/step


In [68]:
for i in range(len(y_pred)):
    if y_pred[i] >= 0.5 :
        y_pred[i] = 1 
    else : 
        y_pred[i] = 0

In [70]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_test,y_pred)

0.9070428696412949